### ISSUE TITLE
HTTP 401: Invalid credentials

### ISSUE THREAD

**Issue by chaofanx** [CNDRD/siegeapi#22]
I modified the mail, password and uid according to the demo code on the homepage of the repo, but after running the code, I got the following error

```
Traceback (most recent call last):
  File "d:\project\demo\main.py", line 28, in <module>
    asyncio.run(sample())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\project\demo\main.py", line 6, in sample
    player = await auth.get_player(uid="2ebxxx157")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\demo\Lib\site-packages\siegeapi\auth.py", line 288, in get_player
    results = await self._find_players(name=name, platform=platform, uid=uid)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\demo\Lib\site-packages\siegeapi\auth.py", line 80, in _find_players
    data = await self.get(f"https://public-ubiservices.ubi.com/v3/users/{uid}/profiles?"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\project\demo\Lib\site-packages\siegeapi\auth.py", line 236, in get
    raise last_error
  File "d:\project\demo\Lib\site-packages\siegeapi\auth.py", line 227, in get
    await self.connect()
  File "d:\project\demo\Lib\site-packages\siegeapi\auth.py", line 212, in connect
    raise FailedToConnect(message)
siegeapi.exceptions.FailedToConnect: HTTP 401: Invalid credentials
```

**Comment by CNDRD** [comment]
???
The error very clearly states what is wrong

**Comment by chaofanx** [comment]
> ??? The error very clearly states what is wrong

But in fact, my network is normal and chrome can open ubisoft's webpage normally. I don't know what's the problem here.

**Comment by CNDRD** [comment]
`HTTP 401: Invalid credentials`
